version: '3.8'

services:
  auth:
    image: blockMeds/auth
    env_file:
      - ./authenticationService/.env
    ports:
      - "5001:5001"

  contract:
    image: blockMeds/contract
    env_file:
      - ./blockchainService/.env
    ports:
      - "3000:3000"
  
  gateway:
    image: blockMeds/gateway
    env_file:
      - ./gatewayService/.env
    ports:
      - "5000:5000"